# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
      platform: x64
    - nodejs_version: 6
      platform: x86
    - nodejs_version: 7
      platform: x64
    - nodejs_version: 7
      platform: x86

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

test_script:
  - npm test

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
