# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8

platform:
  - x86
  - x64

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g install npm@5
  - npm install

test_script:
  - npm test

cache:
  # global npm cache
  - '%APPDATA%\npm-cache'

  # global Yarn cache
  - "%LOCALAPPDATA%\\Yarn"
